### ISSUE TITLE
브랜치 관리 관련하여

### ISSUE THREAD

**Issue by HaenaraShin** [Heavybros/PythonStudy#14]
전부다 master 브랜치에 쓰고 있는데
스터디 하는 사람마다 이름으로 branch 따고, 
최종적으로 작업 완료할 때 master에 병합시키는 식으로 관리하면
조금 깔끔해 지지 않을까? 해서 제안해봅니다.

의견 부탁해.

**Comment by HaenaraShin** [comment]
아무도 의견 안주길래 일단 master 브랜치 강제 Push 막아두었습니다.
특정 브랜치에 대해 push 막는 방법은 아래 링크 참고.
https://help.github.com/en/github/administering-a-repository/enabling-branch-restrictions

**Comment by kirdi-1206** [comment]
브랜치 지금 봤다. 각자 브랜치 따서 하는거 환영이야

**Comment by HaenaraShin** [comment]
브랜치 이름은 study/각자이름 또는 dev/각자이름 이런식으로 하면 되지 싶은데

**Comment by HaenaraShin** [comment]
댓글달고 보니 이미 기수가 Kisoo 해서 만들었으니 그냥 각자 이름으로 따자ㅋㅋ

**Comment by HaenaraShin** [comment]
기수와 내거 브랜치는 각자만 푸시할 수 있도록 rule 설정해 두었음.
https://github.com/Heavybros/PythonStudy/settings/branches
@PhantomG7 형준이도 브랜치 생성하면 rule 설정해줄게
덤으로 master 브랜치는 Pull request 병합 할 때 최소 1명 이상의 review 승인이 필요하도록 설정했어

**Comment by PhantomG7** [comment]
브랜치 추가했어 :)
