### ISSUE TITLE
파이썬 코딩 컨벤션

### ISSUE THREAD

**Issue by HaenaraShin** [Heavybros/PythonStudy#15]

**Comment by HaenaraShin** [comment]
원근님의 리뷰를 받으니 코딩컨벤션을 추가 해야겠다는 생각이 들었습니다.
파이썬에서는 PEP8을 많이들 따른다고들 하는데 
README 에 코딩컨벤션 관련된 내용을 추가해주시면 어떨까 싶네요.

**Comment by HaenaraShin** [comment]
@guppystail2 PEP8 공식자료 + 번역자료 링크랑 설명 간략히 정리해서 별도의 참고페이지 markdown으로 작성한뒤 README에 링크 걸어서 PR 날려주세요

**Comment by HaenaraShin** [comment]
@guppystail2 
이번주 중에는 해줄거죠?

**Comment by guppystail2** [comment]
ㅂㄷㅂㄷ 넹 주인님 도비는 자유의 몸이 아니에요

**Comment by guppystail2** [comment]
네 오빠

나의 iPhone에서 보냄

**Comment by HaenaraShin** [comment]
@guppystail2 내용이 너무 많을 것 같으면 중간단계에서 한번 커밋하고 같이 작업하는 것도 좋을 듯

**Comment by HaenaraShin** [comment]
#23 
병합했으므로 해당 이슈는 클로즈하는걸로
